[package]
name = "algebrisk"
version = "0.0.1"
authors = ["Nick Hilton <nhilton777@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies.windows]
version = "0.39.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
]